### PR TITLE
Sundry

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by turion** [comment]
Note that `sequenceArrList`, while unsafe, doesn't need the `ArrowChoice` instance, which is an advantage over `sequenceArrListZip`. Maybe we can keep both, and make `sequenceArrList` internal (not public)? It can be safely accessed over the `Vec` interface.

**Comment by miguel-negrao** [comment]
> Note that `sequenceArrList`, while unsafe, doesn't need the `ArrowChoice` instance, which is an advantage over `sequenceArrListZip`. Maybe we can keep both, and make `sequenceArrList` internal (not public)? It can be safely accessed over the `Vec` interface.

That's true, good point. I agree lets keep sequenceArrList for internal use, which makes sequenceArrVec not need ArrowChoice. I think you just need to add sequenceArrListZip to the export list, right ?

**Comment by miguel-negrao** [comment]
I'm ready to merge, if you think all is okay.

**Comment by turion** [comment]
I've added a few things ;)

**Pull request merged**
